version: '3.7'

services:

  sample:
    container_name: tickurtimefrontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/tickUrTime/frontend'
      - '/tickUrTime/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
